version: '3.8'
services:
  ts-api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    deploy:
      resources:
        limits:
          memory: 256M
    env_file: ./.env
    restart: always
    command: npm run start:prod
    container_name: ${API_CONTAINER_NAME}
    ports:
      - $APP_PORT:$APP_DOCKER_PORT
    networks:
      - api
      - db
    depends_on:
      - mysqldb
    environment:
      DB_HOST: mysqldb
      NODE_ENV: production
      PRODUCTION: production

  mysqldb:
    image: mysql:${DB_VERSION}
    deploy:
      resources:
        limits:
          memory: 380M
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    container_name: ${DB_CONTAINER_NAME}
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    networks:
      - db
    volumes:
      - ts-api-mysql:/var/lib/mysql
      - ts-api-mysql_config:/etc/mysql

volumes:
  ts-api-mysql:
  ts-api-mysql_config:
networks:
  api: {}
  db: {}
