FROM node:14

RUN mkdir -p /home/node/app && chown -R node:node /home/node/app

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

WORKDIR /home/node/app

COPY . .

RUN /bin/bash -c "source ./scripts/setup-env.sh"

RUN npm install -g pm2

RUN npm install

RUN npm run build:prod

EXPOSE 80 3306

USER node

CMD [ "npm", "run", "pm2:container" ]